---
- name: Clone repo, build, and run jar
  hosts: selenium-test-server
  become: yes
  tasks:
    - name: Clone the repository
      git:
        repo: https://github.com/flopez98/insure-me-app-selenium.git
        dest: /home/ubuntu/app
        version: main

    - name: Change directory to the cloned repo
      shell: cd /home/ubuntu/app

    - name: Run Maven clean install
      shell: mvn clean package assembly:single

    - name: Run the Java jar file
      shell: java -jar /home/ubuntu/app/target/facebook-automation-0.0.1-SNAPSHOT-jar-with-dependencies.jar
